# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

steps:
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: 'build'
    azure_static_web_apps_api_token: $(deployment_token)